# Generated by Django 4.2.18 on 2025-01-22 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='introduction',
            field=models.TextField(blank=True, help_text='Introduction', null=True),
        ),
    ]
