# Generated by Django 4.2.18 on 2025-01-22 21:23

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_post_introduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='introduction',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Introduction', null=True, verbose_name='Introduction'),
        ),
    ]
