# Generated by Django 4.2.18 on 2025-03-30 10:03

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_post_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='introduction',
            field=tinymce.models.HTMLField(blank=True, help_text='Introduction', null=True, verbose_name='Introduction'),
        ),
    ]
