# Generated by Django 4.2.18 on 2025-03-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_post_introduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='introduction',
            field=models.TextField(blank=True, help_text='Introduction', null=True, verbose_name='Introduction'),
        ),
    ]
