# Generated by Django 4.2.18 on 2025-03-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_post_content_alter_post_introduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show this post at the top of the listing'),
        ),
    ]
