# Generated by Django 4.2.18 on 2025-03-30 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_post_content_alter_post_introduction'),
        ('news', '0005_post_is_featured'),
    ]

    operations = [
    ]
