# Generated by Django 5.2.4 on 2025-10-15 11:39

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(default='Djangify', max_length=150)),
                ('business_paragraph', models.TextField(help_text='Short paragraph about the business for footer display.')),
                ('social_1_name', models.CharField(blank=True, help_text='e.g. LinkedIn', max_length=50, null=True)),
                ('social_1_url', models.URLField(blank=True, null=True)),
                ('social_2_name', models.CharField(blank=True, help_text='e.g. Instagram', max_length=50, null=True)),
                ('social_2_url', models.URLField(blank=True, null=True)),
                ('copyright_text', models.CharField(blank=True, help_text='Optional custom copyright text. Leave blank to auto-generate.', max_length=200)),
                ('about_image', models.ImageField(blank=True, help_text='Image appears above title in the left column.', null=True, upload_to='homepage/')),
                ('about_title', models.CharField(default='From Ideas To Income', max_length=150)),
                ('about_text', tinymce.models.HTMLField(help_text='Main body text for the About box section on the homepage.')),
                ('about_cta_text', models.CharField(blank=True, help_text='Optional small CTA below paragraph.', max_length=150, null=True)),
                ('about_cta_link', models.URLField(blank=True, null=True)),
                ('cta_title', models.CharField(default='Free Download: Your First Digital Product Planner', max_length=200)),
                ('cta_text', tinymce.models.HTMLField(blank=True, help_text='Intro text for the CTA box.', null=True)),
                ('cta_bullets', models.TextField(blank=True, help_text='Each bullet on a new line. These will be rendered as a list.', null=True)),
                ('cta_button_text', models.CharField(default='Download The Planner', max_length=100)),
                ('cta_button_link', models.URLField(blank=True, null=True)),
                ('cta_secondary_text', models.CharField(blank=True, default='Explore Our Shop', max_length=100)),
                ('cta_secondary_link', models.URLField(blank=True, null=True)),
                ('cta_image', models.ImageField(blank=True, null=True, upload_to='homepage/')),
                ('cta_pdf_upload', models.FileField(blank=True, null=True, upload_to='homepage/pdfs/')),
                ('blog_section_title', models.CharField(default='Latest Blog Posts', help_text='Displayed above the blog posts grid.', max_length=150)),
                ('blog_section_intro', models.TextField(blank=True, help_text='Short paragraph introducing the blog section (500 words or less).', max_length=500, null=True)),
                ('featured_products_title', models.CharField(default='Featured Products', max_length=150)),
                ('additional_products_title', models.CharField(default='More to Explore', help_text='Title for the automatically loaded additional products section.', max_length=150)),
                ('homepage_intro', models.TextField(blank=True, help_text='Optional tagline or banner at the top of the homepage.', null=True)),
                ('announcement_bar_text', models.CharField(blank=True, help_text="Optional top bar message (e.g. 'Now booking January 2026 projects').", max_length=200, null=True)),
                ('seo_meta_title', models.CharField(blank=True, max_length=150, null=True)),
                ('seo_meta_description', models.CharField(blank=True, max_length=255, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Home Page Settings',
                'verbose_name_plural': 'Home Page Settings',
            },
        ),
    ]
