# Generated by Django 5.2.4 on 2025-10-15 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_homepagesettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagesettings',
            name='cta_bullets',
        ),
    ]
