# Generated by Django 5.2.4 on 2025-10-15 15:23

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_homepagesettings_cta_bullets'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesettings',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='homepage/hero/'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='about_image',
            field=models.ImageField(blank=True, help_text='Upload a small logo image (max display size 128×128px)', null=True, upload_to='homepage/'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='about_text',
            field=tinymce.models.HTMLField(help_text='Text for the About box section - 70 WORDS with and image 100 WORDS without is recommended.'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='about_title',
            field=models.CharField(default='Your Title Here', max_length=150),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='cta_button_text',
            field=models.CharField(default='Here Is Your Download', max_length=100),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='cta_title',
            field=models.CharField(default='Free Download: Title For Your Download', max_length=200),
        ),
    ]
