# Generated by Django 5.2.4 on 2025-10-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_homepagesettings_hero_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagesettings',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Optional hero background image (recommended 700×500px).', null=True, upload_to='homepage/hero/'),
        ),
    ]
