# Generated by Django 5.2.4 on 2025-10-15 18:17

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_homepagesettings_hero_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesettings',
            name='hero_paragraph',
            field=models.TextField(blank=True, help_text='Supporting 1–2 sentences displayed below the hero title.', null=True, verbose_name='Hero Paragraph'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='hero_title',
            field=models.CharField(default='Your Main Title', help_text='Main heading text displayed in the hero section.', max_length=150, verbose_name='Hero Title'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='logo_image',
            field=models.ImageField(blank=True, help_text='Optional logo to display in the navbar beside the business name.', null=True, upload_to='homepage/logo/', verbose_name='Logo Image'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='about_text',
            field=tinymce.models.HTMLField(help_text='Text for the About box section – around 70–100 words recommended.'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='additional_products_title',
            field=models.CharField(default='More to Explore', max_length=150),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='announcement_bar_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='business_name',
            field=models.CharField(default='Djangify', help_text='Displayed in the site navbar next to the logo.', max_length=150, verbose_name='Business Name'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='business_paragraph',
            field=models.TextField(blank=True, help_text='Old hero paragraph, now replaced by hero_paragraph. Safe to delete once migrated.', null=True, verbose_name='Deprecated – previously Hero Paragraph'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='homepage_intro',
            field=models.TextField(blank=True, null=True),
        ),
    ]
