# Generated by Django 5.2.4 on 2025-10-17 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_homepagesettings_hero_paragraph_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagesettings',
            name='business_name',
            field=models.CharField(default='Djangify', help_text='Displayed in the navbar next to the logo.', max_length=150, verbose_name='Business Name'),
        ),
    ]
