# Generated by Django 5.2.4 on 2025-07-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_verified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memberresource',
            options={'ordering': ['order', '-created_at']},
        ),
        migrations.AddField(
            model_name='memberresource',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
