# Generated by Django 4.2.18 on 2025-03-30 10:03

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=tinymce.models.HTMLField(max_length=200),
        ),
    ]
