# Generated by Django 5.2.4 on 2025-08-01 18:56

import inspirational.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_long_description_product_section_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='files',
            field=models.FileField(blank=True, help_text='Upload a PDF or ZIP file. Use ZIP for bundles.', null=True, storage=inspirational.storage.SecureFileStorage(), upload_to='products/files/'),
        ),
    ]
