# Generated by Django 5.2.4 on 2025-08-06 15:39

import inspirational.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_product_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload a short MP4 file to display as product video', null=True, storage=inspirational.storage.PublicMediaStorage(), upload_to='products/videos/'),
        ),
        migrations.AddField(
            model_name='product',
            name='video_url',
            field=models.URLField(blank=True, help_text='Optional YouTube or Vimeo URL to display on the product page', null=True),
        ),
    ]
