# Generated by Django 4.2.18 on 2025-03-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_portfolio_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='architecture_description',
            field=models.TextField(blank=True, help_text='Explanation of architecture and design patterns used', null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='bugs_and_fixes',
            field=models.TextField(blank=True, help_text='Significant issues encountered and their resolutions', null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='business_logic',
            field=models.TextField(blank=True, help_text='The problem statement and business logic of the project', null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='challenges',
            field=models.TextField(blank=True, help_text='Technical hurdles faced and how they were overcome', null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='conclusion',
            field=models.TextField(blank=True, help_text='Summary of the project experience', null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='demo_video_url',
            field=models.URLField(blank=True, help_text='URL to a demo video (e.g., YouTube)', null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='development_process',
            field=models.TextField(blank=True, help_text='Approach and methodologies used during development', null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='future_improvements',
            field=models.TextField(blank=True, help_text='Planned or potential future enhancements', null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='lessons_learned',
            field=models.TextField(blank=True, help_text='Technical and project management insights gained', null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='outcome',
            field=models.TextField(blank=True, help_text='How the project meets its objectives', null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='project_timeline',
            field=models.CharField(blank=True, help_text="When the project was built, e.g., 'Jan-Mar 2023'", max_length=100),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='target_audience',
            field=models.TextField(blank=True, help_text='Description of who the project is designed for', null=True),
        ),
    ]
