# Generated by Django 5.1 on 2025-03-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_portfolio_architecture_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
